name: Screenshots

on:
  workflow_dispatch:

jobs:
  app-store-screenshots:
    name: Generate App Store screenshots
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 26.4.1
        run: sudo xcode-select -s /Applications/Xcode_26.4.1.app/Contents/Developer

      - name: Xcode version
        run: xcodebuild -version

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Generate screenshots
        run: bundle exec fastlane screenshots

      - name: Upload screenshots artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-store-screenshots
          path: screenshots/
